### ISSUE TITLE
Question: Are nested properties supported?

### ISSUE THREAD

**Issue by christianplatta1012** [jcrist/msgspec#171]
Hi,
first thank you for your amazing work with this library. Is is unbelievable how much faster msgspec is compared to other json parser for python!
Is it possible to define nested properties in msgspec without defining a new Struct for each nesting level?
E.g.:
json:
{  "a":  {
       "b" : { "c"  :1}
       }
       ... many more properties ...
}

I want to only map "c". Can this be done without creating a Struct for "a" and "b" as well?

Best regards,
Christian

**Comment by jcrist** [comment]
Apologies for the delayed response here.

When using a typed decoder, `msgspec` requires a full type hierarchy down to the field(s) you want to decode. You need to define a Struct (or other type) for each level.

If you only have a few of these I might write them out manually, but another option is to use [`msgspec.defstruct`](https://jcristharif.com/msgspec/api.html#msgspec.defstruct) to automatically define these at runtime.

Here's an example of how this might work:

```python
import operator

import msgspec


def make_decode_for(type, prefix=""):
    # Construct simple struct types at runtime modeling the prefix.  Each type
    # has a single field (the part of the prefix).
    for field in reversed(prefix.split(".")):
        type = msgspec.defstruct(f"prefix_{field}", [(field, type)])

    # Create a decoder for the type
    dec = msgspec.json.Decoder(type)

    if prefix:
        # Create a new `decode` method that decodes a prefixed type, then uses
        # attrgetter to extract the desired subfield.
        getter = operator.attrgetter(prefix)

        def decode(msg):
            return getter(dec.decode(msg))

        return decode
    else:
        return dec.decode


class C(msgspec.Struct):
    x: int
    y: int


# Make a new `decode` function for decoding `C`, dropping the prefix `a.b`
decode = make_decode_for(C, prefix="a.b")

msg = b'{"a": {"b": {"x": 1, "y": 2}}}'

print(decode(msg))
# outputs "C(x=1, y=2)"
```

Note that when using something like this you only want to call `make_decode_for` once for each type + prefix combination, since constructing a new `decode` function is a modestly expensive operation. Once generated, the `decode` function can be called multiple times with negligible overhead.

Does that answer your question?

**Comment by jcrist** [comment]
Closing as inactive, feel free to reach out if you have more questions.
