### ISSUE TITLE
Incompatibility with `mypyc`

### ISSUE THREAD

**Issue by MaximZayats** [jcrist/msgspec#194]
Hi!

When I tried to run the compiled code, I found some problems.
Not sure if this is a problem with `msgspec` or `mypyc`.

1)
```python
import msgspec

class MyStruct(msgspec.Struct):
    a: int
```

Error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "demo/main.py", line 4, in <module>
    class MyStruct(msgspec.Struct):
KeyError: 'Struct'
```

2)
```python
import msgspec
from msgspec import Struct


class MyStruct(Struct):
    a: int | str
    b: int


decoder = msgspec.json.Decoder(MyStruct)

decoded = decoder.decode(b'{"a": 1, "b": 2}')
```

Error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "demo/main.py", line 12, in <module>
    decoded = decoder.decode(b'{"a": 1, "b": 2}')
msgspec.ValidationError: Expected `type`, got `int` - at `$.a`
```

To compile: `mypyc demo`
To run: `python3.10 -c "import demo.main"`
Mypy: `mypy 0.981 (compiled: yes)`

**Comment by jcrist** [comment]
Hmmm, I'm not sure what's going on here. I don't have any experience with `mypyc` - since `msgspec` programs pass mypy's type checker, my first guess is this points to bugs in `mypyc`. `msgpsec` does do a lot of cpython VM magic though, so there may be things we're doing that lead to incompatibilities. Not sure.

Are you successfully using `mypyc` elsewhere, or were you just trying it out with msgspec?
