### ISSUE TITLE
JSON encoding corrupts binary data

### ISSUE THREAD

**Issue by inklesspen** [jcrist/msgspec#215]
I was storing data related to tweets, including author avatar images, in a JSON file, and the binary image data became corrupted. However, this data does not get corrupted when using msgpack.

Here is a simple example:
```python
import typing

import msgspec
import requests


class Image(msgspec.Struct):
    url: str
    imagebytes: typing.Optional[bytes] = None


class Important(msgspec.Struct):
    message: str
    image: Image


def fetch(image: Image):
    r = requests.get(image.url)
    r.raise_for_status()
    image.imagebytes = r.content


def main():
    image = Image(url="https://placekitten.com/256/256")
    fetch(image)
    valued_data = Important(message="Hello world", image=image)
    with open("test.json", "wb") as out:
        out.write(msgspec.json.encode(valued_data))

    decoder = msgspec.json.Decoder(Important)
    decoded = decoder.decode(open("test.json", "rb").read())

    if decoded.image.imagebytes != image.imagebytes:
        raise ValueError("changed!")


if __name__ == "__main__":
    main()
```

**Comment by jcrist** [comment]
Thanks for opening this and for including an excellent reproducible example!

This was due to a small (in # of lines of code, not in impact :grimacing:) bug in the base64 encoding routine used by msgspec. This is fixed in #217, which also expands our test suite to provide better coverage here.

I'm hoping cut a new release `msgspec` in a few weeks, but until then you can install from source:

```
pip install git+https://github.com/jcrist/msgspec.git
```

Please let me know if you run into any further issues.
