### ISSUE TITLE
Enhancement: Support Pydantic Types

### ISSUE THREAD

**Issue by Goldziher** [jcrist/msgspec#216]
Hi there again! We've begun integrating msgspec into Starlite! I'd like to request a feature - support Pydantic Types and custom types. This requires supporting the `__get_validators__` and calling it for any type that implements it. I understand this is going to suboptimal in terms of performance probably, but it's really necessary to support migrating our internal parsing logic without breaking users stuff in unacceptable ways. Also, it's going to benefit anyone else who looks for Pydantic interop.

**Comment by jcrist** [comment]
Can you comment more on how you see msgspec working with pydantic?

I wouldn't recommend mixing them really. Encoding/decoding pydantic objects using msgspec will currently be as performant as pydantic V1 doing it natively, but once pydantic V2 is out that will no longer be true (msgspec is still measurably faster than pydantic V2, just not for pydantic-specific types). Rather, I'd recommend using pydantic to encode/decode pydantic types, and msgspec to encode/decode everything else. Perhaps make the serialization/validation library used by starlite configurable rather than hardcoding a specific library? This way you don't have to worry about the boundaries between libraries.

If you really want to have msgspec work with pydantic types, this can be done today using the existing [extensions mechanism](https://jcristharif.com/msgspec/extending.html) (with some caveats):

```python
import msgspec
import pydantic


class Point(pydantic.BaseModel):
    x: int
    y: int


class Outer(msgspec.Struct):
    point: Point


def dec_hook(type, obj):
    if issubclass(type, pydantic.BaseModel):
        return type(**obj)
    elif hasattr(type, "__get_validators__"):
        # Left as an exercise for the reader
        raise NotImplementedError
    raise TypeError(f"Don't know how to decode into {type}")


def enc_hook(obj):
    if isinstance(obj, pydantic.BaseModel):
        return obj.dict()
    raise TypeError(f"Don't know how to encode {type}")


enc = msgspec.json.Encoder(enc_hook=enc_hook)
dec = msgspec.json.Decoder(Outer, dec_hook=dec_hook)


x = Outer(Point(x=1, y=2))

msg = enc.encode(x)
x2 = dec.decode(msg)
assert x == x2
```

I'm not going to add native support for pydantic types, but would be happy to make any changes needed to the extension mechanism to support your use case.

**Comment by Goldziher** [comment]
Hi, so I wouldn't bother too much with the performance - its not an issue. The issue though is that users might be using pydantic specific types, and we will need to parse and handle these. I don't want to force a breaking change on users, so I would like to be able to support parsing these types. This is not so much about json, although its also about json, but more about parsing a primitive value into a pydantic type by calling the class method.
