### ISSUE TITLE
Inconsistent support of subclassed types

### ISSUE THREAD

**Issue by provinzkraut** [jcrist/msgspec#248]
When trying to encode subclasses of supported types, some will result in a `TypeError`, while others work as expected. It would be great to either support subclasses in general, or at least have an explanation of these limitations in the docs. 

For comparison, the below example is supported by `json`, `orjson` and `ujson`.

```python
import msgspec


class CustomList(list):
    pass


class CustomStr(str):
    pass


msgspec.json.encode(CustomList())  # this works
msgspec.json.encode(CustomStr())  # this is a TypeError
```

**Comment by jcrist** [comment]
Only subclasses of `list` and `dict` are supported, the rest require usage of an `enc_hook`. This is documented [in the type list here](https://jcristharif.com/msgspec/usage.html#typed-decoding), but could definitely be repeated elsewhere. Where in the docs did you look for it (putting information where people will look for it can be hard sometimes)?

Note that `orjson` only supports subclasses of `list`, `dict`, `int`, and `str` - all other subclasses will require a `default` hook there. We choose not to support `int` and `str`.

The reasoning behind this decision is that usually when someone subclasses a collection it's to modify some runtime behavior (`defaultdict`, `OrderedDict`, ...), the way that collection serializes usually doesn't change.

In constrast, when someone subclasses a scalar like `int`/`str`, they sometimes do so to change a serialization behavior. For example, I know of one user who is subclassing `int` to support encoding integers as hex strings. If we supported all subclasses natively, there'd be no way to change the encode/decode behavior for scalar subclasses in msgspec.

Does that explanation make sense?

**Comment by provinzkraut** [comment]
> This is documented [in the type list here](https://jcristharif.com/msgspec/usage.html#typed-decoding), but could definitely be repeated elsewhere

Huh, I actually looked for a mention of this in the docs but couldn't find it. 

> Does that explanation make sense?

It does, yes!

> In constrast, when someone subclasses a scalar like int/str, they sometimes do so to change a serialization behavior. 

I guess that depends on your target audience. Our target audience for example is most likely doing it for validation purposes, since it's a pattern promoted by Pydantic.

**Comment by Goldziher** [comment]
> In constrast, when someone subclasses a scalar like `int`/`str`, they sometimes do so to change a serialization behavior. For example, I know of one user who is subclassing `int` to support encoding integers as hex strings. If we supported all subclasses natively, there'd be no way to change the encode/decode behavior for scalar subclasses in msgspec.

Well, this is problematic - this is an assumption regarding what is happening on the user's end. Another primary reason to subclass int, str, float etc. is to customize representation rather than serialization.  

Would it be possible for msgspec to use hooks for types if present otherwise default to using default behaviour?

i.e. - if a user defines a hook to serialize `int`, use the hook, otherwise use default serialization. If a user defines a hooke for a subclass of `int` prefer this hook, otherwise a hook for the superclass, if defined, otherwise default serialization?

**Comment by jcrist** [comment]
Thanks @provinzkraut! I'll push a PR up to clarify things better in the documentation.

I'll also add support for subclasses of `set`/`frozenset` for uniformity, so subclasses of all builtin collection types are treated the same.

> Would it be possible for msgspec to use hooks for types if present otherwise default to using default behaviour?

The current extension mechanism only supports a callable - to determine if the user has overridden support for a subclass of a type, we'd have to call that callable, and on error fallback to default support. That would be less efficient than having the user manually support subclasses they way they want to in the `enc_hook` callback. The only difference between `msgspec` and `orjson` here is that we don't support `str` and `int` subclasses natively - you'd still need to handle e.g. `float` subclasses yourself with `orjson`.

In the future I hope to redesign the extension mechanism to be more granular (rather than a single callable) - with that we could do what you're asking in an efficient manner. But as things stand what @provinzkraut did in https://github.com/starlite-api/starlite/pull/1011 is the most efficient thing available.

**Comment by Goldziher** [comment]
cool, thanks

**Comment by provinzkraut** [comment]
> I'll also add support for subclasses of set/frozenset for uniformity, so subclasses of all builtin collection types are treated the same.

Very nice! 

> The current extension mechanism only supports a callable - to determine if the user has overridden support for a subclass of a type, we'd have to call that callable, and on error fallback to default support. That would be less efficient than having the user manually support subclasses they way they want to in the enc_hook callback

Shouldn't it be possible to make this process quite efficient, if instead of a callable, the user can provide a mapping (like we do in Starlite), which then could be checked against overrides? This could become even less costly if done with an `Encoder` instance, since you could (presumably?) only do the checking once. That's just some guesswork though, since admittedly, my C isn't that great, which makes the 15,000 loc behemoth you created quite intimidating (:upside_down_face:), so I'm not that familiar with msgspec's internal workings.

I still think it would be a nice addition to have, since it makes msgspec more adaptable, even if it came at a performance cost. IMO, worse performance when using overrides is still better than not being able to override how types are serialized.

**Comment by jcrist** [comment]
> Shouldn't it be possible to make this process quite efficient, if instead of a callable, the user can provide a mapping (like we do in Starlite), which then could be checked against overrides?

That's the general idea I'd like to transition to eventually (although I'm planning to do it through a custom `singledispatch`-like-object instead of a raw dict of functions). Doing this for both encoding and decoding opens up opportunities for more efficient and ergonomic custom type support.

> This could become even less costly if done with an Encoder instance, since you could (presumably?) only do the checking once.

Unlike `Decoder`s, `Encoder`s aren't type-specific, so we can't cache that knowledge on the encoder itself. The reason behind using a `singledispatch`-like-object for holding extension callbacks is that we can cache the mro-walking information there. In a hot loop encoding a custom type would then be a single lookup in a `dict` of the type, no mro-walking necessary.

> which makes the 15,000 loc behemoth you created quite intimidating 

From a community perspective I'd really like to increase the bandwidth on this project. There is some low-level performance mucking code in here, but for the most part msgspec is a standard consumer of the CPython c-api. If you'd be interested in helping out here in the future, I'd be happy to:

- Finally write up a contributing doc
- Set aside some good first issues
- Do some reorganizing to make it easier for others to hack on

No pressure though of course.

> I still think it would be a nice addition to have, since it makes msgspec more adaptable, even if it came at a performance cost. IMO, worse performance when using overrides is still better than not being able to override how types are serialized.

I generally agree with this. But all software is tradeoffs. Until I hear from a user with an actual need to change how a collection is serialized, I'll consider these restrictions an easy-win :).

**Comment by provinzkraut** [comment]
> Unlike Decoders, Encoders aren't type-specific, so we can't cache that knowledge on the encoder itself. The reason behind using a singledispatch-like-object for holding extension callbacks is that we can cache the mro-walking information there. In a hot loop encoding a custom type would then be a single lookup in a dict of the type, no mro-walking necessary.

That was essentially what I was thinking of, just with the caching on a per-`Encoder` basis.

> If you'd be interested in helping out here in the future

I'm definitely interested, although I wouldn't want to make any promises as to if and when. But if and when I find the time,
having a contributers doc and the code base aimed a bit more towards outside contributers would definitely make it more likely!
