### ISSUE TITLE
Feature request: evolving a frozen struct (with sample code)

### ISSUE THREAD

**Issue by inklesspen** [jcrist/msgspec#261]
The popular attrs library has a utility function [`evolve`](https://www.attrs.org/en/stable/api.html#attrs.evolve). It is used to make a copy of a frozen object with certain changes applied.

Example:

```python
class Point(msgspec.Struct, frozen=True):
    x: int
    y: int

p = Point(x=150, y=150)
p2 = evolve(p, y=250)
assert p2.x == 150
assert p2.y == 250
```

I created an implementation for my own project, but you may wish to add additional error handling, or perhaps implement it in the C core. I am also not sure which namespace to which it ought to be added.

```python
def evolve(obj: msgspec.Struct, **changes):
    cls = obj.__class__
    for field_name in cls.__struct_fields__:
        if field_name not in changes:
            changes[field_name] = getattr(obj, field_name)
    return cls(**changes)
```

**Comment by jcrist** [comment]
Thanks for opening this issue. Your implementation above is well written, and is how I'd do this without a builtin operation. However, since both `attrs` and `dataclasses` have a builtin function for this, I've added one in #262. I went with calling it `msgspec.replace`, mirroring `dataclasses.replace`/`NamedTuple._replace`/`datetime.replace`/..., since that name seems more common in the python stdlib. The functionality is identical to yours above though.
