### ISSUE TITLE
Consideration for a streaming `Decoder`

### ISSUE THREAD

**Issue by goodboy** [jcrist/msgspec#27]
I was able to get basic funtionality integrated into a project but got hung up on not having an easy way to decode streamed `msgpack` data into objects incrementally.

`msgpack-python` offers the [*streaming* `Unpacker` api](https://github.com/msgpack/msgpack-python#streaming-unpacking) which is [implemented in cython](https://github.com/msgpack/msgpack-python/blob/main/msgpack/_unpacker.pyx#L213).

I would be great to get something similar in this project for convenient stream processing without having to do manual parsing for object message delimiters.

I would be interested to provide a patch for this support. 
Would you accept one as such in `cython` or would you insist on C?

**Comment by jcrist** [comment]
A streaming API for a deserializer is hard to support, since the internal state of the decoder needs to be kept throughout all operations so that it can be resumed later on. This comes with a performance hit for non-streaming decoding, and would complicate the codebase. Implementing it would require changes to the parser statemachine, which is all implemented at the C level (so no, Cython wouldn't work here).

Rather, I recommend implementing message framing at a higher level. A simple protocol would be length prefix framing (see e.g. [this blog post](https://eli.thegreenplace.net/2011/08/02/length-prefix-framing-for-protocol-buffers) for reference). This has a few benefits besides simplifying our codebase:
- It lets you easily swap out the serialization mechanism without changing the framing (so you could try out e.g. json, pickle, quickle, etc...) instead.
- They let you set limits on the message size received, so a client can't send a giant message that would crash the server. This is harder to handle at the msgspec level, but easier at the framing level (where you can set a max size on the total message).

**Comment by goodboy** [comment]
> Rather, I recommend implementing message framing at a higher level.

@jcrist cool, this def makes sense to me.

Are you suggesting that a framing protocol could be added to this project or you're suggesting client code should implement it in its own code base?

Thanks again for the in depth answers btw.

**Comment by jcrist** [comment]
This would be something you'd handle in your own codebase. A naive asyncio implementation might be (untested, please note I don't have these apis memorized):

```python
async def write(stream, msg: bytes) -> None:
    n = len(msg)
    stream.write(n.to_bytes(4, "big"))
    socket.write(msg)
    await stream.drain()

async def read(stream) -> bytes:
    prefix = await stream.readexactly(4)
    n = int.from_bytes(prefix, "big")
    return await stream.readexactly(n)
```

**Comment by goodboy** [comment]
@jcrist if you're ok with it I might also put an example of this in the docs PR for #25 just so any newcomers have an example to work off.  I'll probably link to the protobuf post you sent as well. Imo it'd be pretty handy to have some examples for multiple async frameworks as well.
