### ISSUE TITLE
Allow using mixins and ABCs

### ISSUE THREAD

**Issue by Goldziher** [jcrist/msgspec#296]
### Description

Hi there @jcrist,

Working on integration - as usual. It seems i cant mix a `Struct` with a mixin, ABC or Protocol. Is there any way this can be changed?

It would be great if I could specify a Protocol or an ABC and then use a struct to fulfill it.

**Comment by jcrist** [comment]
This is unfortunately not really possible due to a Python limitation. Python doesn't support multiple metaclasses on a type. Pydantic skirts around this for `abc.ABC` types since its `BaseModel` subclasses from `ABCMeta`, but if you try to mix a `Protocol` and a `BaseModel` you'll get an error.

```python
In [1]: from pydantic import BaseModel

In [2]: from typing import Protocol

In [3]: class Foo(Protocol):
   ...:     def foo(self, x: int) -> int:
   ...:         pass
   ...: 

In [4]: class Model(Foo, BaseModel):
   ...:     a: int
   ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 class Model(Foo, BaseModel):
      2     a: int

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

I'm uninterested in using the same hack here, since subclassing from `abc.ABCMeta` adds measurable runtime overhead on some operations. We also can't use the same hack to support both `abc.ABC` and `typing.Protocol`, and I don't really want to pick a favorite.

---

However! Neither abstract base classes nor protocols require subclassing from them directly, you can define a protocol and implement it in a separate class without subclassing. `runtime_checkable` works, and `mypy` / `pyright` will still be happy.

```python
In [1]: from typing import Protocol

In [2]: from typing import runtime_checkable

In [3]: @runtime_checkable
   ...: class Foo(Protocol):
   ...:     def foo(self, x: int) -> int:
   ...:         pass
   ...: 

In [4]: class ImplementsFoo:
   ...:     def foo(self, x: int) -> int:
   ...:         return x + 1
   ...: 

In [5]: x = ImplementsFoo()

In [6]: isinstance(x, Foo)
Out[6]: True
```

That said, this prevents using that type as a mixin with additional methods.

---

If needed I _could_ be convinced to add support for non-struct mixins (that don't subclass from `Protocol` or `abc.ABC` provided that the mixin:

- doesn't define `__init__`
- defines `__slots__ = ()`

The trick here would be writing up a check that verifies both of these robustly.

**Comment by Goldziher** [comment]
Mixins would be nice, it's pretty restrictive now tbh. 

Alternatively perhaps allow defining custom struct types, let the user decide on required performance etc. You might also have an alternative, somewhat less performant but more flexible struct class - letting users balance these out. 

For pure parsing this will not hinder us, but i think it makes the library harder to work with in user land.
