### ISSUE TITLE
Allow "arbitrary" types to be passed through to_builtins

### ISSUE THREAD

**Issue by Goldziher** [jcrist/msgspec#297]
### Description

Hi @jcrist ,

So I hit another bump that is blocking me - I cant convert a struct with custom values into a dict using `to_builtins`. For example, my struct has an instance of `Request` attached, and i need to pass this value into the dict. Currently its not possible to do. 

Cheers

**Comment by jcrist** [comment]
This doesn't really fit with the design of `to_builtins`. `to_builtins` is for recursively converting a message composed of high-level objects (struct, dataclass, ...)  into one composed of _only_ simple builtin types (list, dict, str, int, bool, None). This is for mainly for supporting alternate serialization libraries (yaml, toml, ...), which typically only support simple builtin types. Passing through a complex type like `Request` doesn't really fit with its design.

Do you need the recursive behavior and type conversions, or are you only trying to convert a ` Struct` to a `dict` (without recursion)? If it's the latter, then you might use the following snippet instead:

```python
def to_dict(self):
    return {f: getattr(self, f) for f in self.__struct_fields__}
```

If that doesn't suit your needs, then I'll need more information about what you're using `to_builtins` for.

Note that if you're always going to convert a `Struct` into a `dict` after decoding, you might use a `TypedDict` to describe your model instead of a `Struct`. These are fully supported in `msgspec`, and would avoid the cost of the type conversion after decoding.

**Comment by Goldziher** [comment]
Hi,

Would typeddicts perform as well as a struct? 

I need to attach classvars and other methods to the class as well. I'm not sure a typeddict would work here.

**Comment by Goldziher** [comment]
As for my use case - i model the signature of functions into what we call a "SignatureModel". 

This model receives values extracted from the request  - path, query, header, cookie parameters, request data, and also different types of framework specific classes such as State, Request etc. and possibly also injected dependencies. 

Some types are indeed python primitives, builtins etc. Others though are custom classes, and can be pretty much any arbitrary value. 

We need a way to quickly and efficiently get a string keyed dict of parsed values. If simply using `getattr` is sufficient that is if course the route to go. I assumed though `to_builtins` would be somewhat faster and more efficent than doing this in plain python.

**Comment by jcrist** [comment]
> Would typeddicts perform as well as a struct?

Depends on what you're doing. Decoding into a `Struct` is faster than decoding into a `TypedDict`. But if you always convert the struct to a dict afterward then decoding into a `TypedDict` originally would be faster.

> We need a way to quickly and efficiently get a string keyed dict of parsed values. If simply using getattr is sufficient that is if course the route to go. I assumed though to_builtins would be somewhat faster and more efficent than doing this in plain python.

For now, yes the `to_dict` implementation I wrote above is the way to do this. We could add a utility function written in C to do this too, but I wouldn't expect a huge speedup. Compared to the cost of user code a dict comprehension like this should be negligible.

---

> I need to attach classvars and other methods to the class as well. I'm not sure a typeddict would work here.

Are any of those methods user facing, or are they for only internal usage? Based on your recent issues (as well as peeping at some of the [code in starlite](https://github.com/starlite-api/starlite/blob/d28690e0ab4f4fec0ba0c4b8b39ee0083445f172/starlite/signature/models.py#L218)), I think you might be better served separating out the code that handles type munging from the actual "model"/struct definition. IIUC right now you have a class with a bunch of classmethods (and class level state) that does the type munging, and specific signatures are subclasses of that type.

What if instead you had something like (pseudocode):

```python
class BaseSignature(Protocol):
    def parse(self, connection: ASGIConnection) -> dict[str, Any]:
        ...

class PydanticSignature(BaseSignature):
    def __init__(self, not_sure_what_args_are_needed_here):
        # Given the handler signature, define a pydantic model and store it on this instance
        # as `model_class`
        self.model_class = ...

    def parse(self, connection: ASGIConnection) -> dict[str, Any]:
        # handle the parsing and conversion to a dict here using pydantic

class MsgspecSignature(BaseSignature):
    def __init__(self, not_sure_what_args_are_needed_here):
        # Given the handler signature, define a msgspec Struct (or a TypedDict?) and store
        # it as `model_class`
        ...
        self.model_class = msgspec.defstruct("Signature", ...)  # TODO

    def parse(self, connection: ASGIConnection) -> dict[str, Any]:
        # handle the parsing and conversion to a dict here using msgspec


signature = PydanticSignature(whatever_args_are_needed_to_provide_the_type_info)
# or 
signature = MsgspecSignature(whatever_args_are_needed_to_provide_the_type_info)
parsed_dict = signature.parse(connection)
```

Hopefully the pseudocode above is clear enough. This design has some nice properties. It doesn't require abstract mixin classes or classmethods on the actual BaseModel/Struct types, the type munging code is pulled out to instances of an outer class. The generated types used by the various parsing libraries (pydantic or msgspec) are hidden in their respective `BaseSignature` implementations - they're an implementation detail.

**Comment by jcrist** [comment]
I've opened an issue for adding a native version of the `to_dict` utility described above #299. I doubt this perf would matter much in most real world use, but they're easy utilities to write.

**Comment by Goldziher** [comment]
Great stuff. Your suggestion is certainly an option. It's simply a bit more complex, but it'l might be the way to go.

**Comment by jcrist** [comment]
With #299 in there's now `msgspec.structs.asdict` ([docs](https://jcristharif.com/msgspec/api.html#msgspec.structs.asdict)) which does a shallow conversion of a Struct to a dict. It's a native equivalent to the following (still valid) pure python code:

```python
def asdict(self):
    return {f: getattr(self, f) for f in self.__struct_fields__}
```

Since you're not doing any conversions and don't want the recursive behavior of `to_builtins` you should use either of these instead.

I believe this issue should be resolved, closing.
