### ISSUE TITLE
Show only non-defaults when omit_defaults is set

### ISSUE THREAD

**Issue by rsmb7z** [jcrist/msgspec#309]
### Description

Hi,
When `omit_defaults=True` is set, it works for the encoding however repr shows all the types. It would be good to show only non-default values in repr when this flag is set.

**Comment by jcrist** [comment]
Can you say more about why you'd want that behavior? What's your use case?

I'm not sure coupling a simpler repr to `omit_defaults` makes sense (`omit_defaults` is about encoding, not repr-ing). I'd thought about omitting default values from the `repr` for all structs, but nixed it since neither `dataclasses`, `attrs`, nor `pydantic` do this.

**Comment by rsmb7z** [comment]
Hi @jcrist 
Yes I understand that `omit_defaults` is specific to encoding originally however having different flag will be okay too.
Similar to performance improvment with `omit_defaults` during encoding, I would prefer to view only arguments which are non-defaults. Expected behavior you will find here for `Contract` class.
https://github.com/erdewit/ib_insync/blob/master/ib_insync/contract.py

**Comment by jcrist** [comment]
I've added a new `repr_omit_defaults` option in #322 that should do what you want.

**Comment by ml31415** [comment]
This new option should probably be mentioned in the docs on the website as well.
