### ISSUE TITLE
Question: Override Decimal behavior

### ISSUE THREAD

**Issue by madisonleavo** [jcrist/msgspec#321]
### Description

Regarding #288 is there a way to override and serialize as a `float` ? I use 0.12.0 and was surprised at breaking change in 0.13.x. 

I know your views on Decimal representation should be in string, but we store our numbers as Decimal in database because the compression is better. I do not care about the exact representation - but I do care that the value is serialized as "numeric"

I'm doing this now in 0.12.0 - how should I do this going forward?

```python
def enc_hook(obj: Any) -> Any:
    if isinstance(obj, Decimal):
        if obj.as_integer_ratio()[1] == 1:
            return int(obj)
        else:
            return float(obj)
```

**Comment by jcrist** [comment]
Thanks for opening this issue, and I'm sorry to hear that we broke your code. Unfortunately there's no way to override this behavior currently.

A few options:

- If you're only storing the objects as decimals in the DB, but never working with them intentionally as decimals, you may be able to configure your database driver/ORM to convert these fields to floats or ints when reading, so you never end up with a `Decimal` object in python. I know this is possible with sqlalchemy, but there's likely a way to do it with other tools. If this is possible, I think this would be the best option.
- If you do need to treat these objects as decimal objects at the python layer, you may be able to subclass `Decimal`, and configure your DB driver/ORM to return your decimal subclass instead. `msgspec` only overrides how `decimal.Decimal` instances are encoded, not subclasses of `decimal.Decimal.
- Alternatively, could you convert the decimals to floats/ints before they reach the serialization layer? This may require some manual code changes on your end, but may not be that bad. An added benefit is this will be more efficient than anything `msgspec` could do, since it would avoid a bunch of extra branches on our end.

If none of those options work for you, then you'll need to wait for us to redo our extension mechanism before upgrading. This is on my shortlist of features to implement, but is a pretty large change. I'd guess this work will be completed in 2-4 months.

**Comment by jcrist** [comment]
Closing as answered.
