### ISSUE TITLE
inspect raises exception on union

### ISSUE THREAD

**Issue by Goldziher** [jcrist/msgspec#325]
### Description

Hi @jcrist,

I guess this is by design but it doesn't work for us and this is another blocker for integration... (i resumed work, and 15 minutes in encountered this):

The following `Optional[Union[int, datetime, date]]` causes the following exception:

```shell
TypeError: Type unions may not contain more than one str-like type (`str`, `Enum`, `Literal[str values]`, `datetime`, `date`, `time`, `uuid`, `decimal`, `bytes`, `bytearray`) - type `typing.Union[int, datetime.datetime, datetime.date, NoneType]` is not supported
```

We have to support this kind of unions. We use typing data to generate open api sepcification, for example, and our users might be using more lax unions. This is too strict for our use cases. Is it possible to either make the check more lax or offer configuration to `inspect.type_info` to turn off validation? Some validation might be useful, but this is something we really can't handle im afraid.

**Comment by jcrist** [comment]
`inspect` handles types the same way our decoders do. `msgspec.json.decode` is unable to handle parsing that type. See the docs on unions [here](https://jcristharif.com/msgspec/supported-types.html#union-optional).

Is the ask here to make `inspect.type_info` not error in this case? We could remove these checks so any type combination would pass through here, but you'd just get an error later at runtime when parsing with msgspec.

Alternatively we could make this specific case (`Union[date, datetime]`) work. Unlike pydantic, `msgspec` won't allow type annotations that would lead to ambiguous parsing. This means that any union type may have at most one type that maps to each of the JSON types (e.g. one type that encodes as a `str`, one type that encodes as a `number`, one type that encodes as an `object`, ...). In *this particular case* we could relax this check to allow mixing `date` and `datetime` fields, but there will always be cases that we must disallow to prevent ambiguity (e.g. `Union[datetime, bytes]`, since RFC3339 timestamps may also be valid base64 values).

**Comment by Goldziher** [comment]
Thanks for clarifying  This is not merely about date and datetime. There are any number of combinations that are valid in user land and will error here. For example `Enum`, `Literal[str values]`, would defintely be a problem. 

This issue basically means we can't use msgspec to decode to a wide range of data that might be defined by users. 

I think we can agree we have different use cases in mind.

**Comment by jcrist** [comment]
> For example `Enum`, `Literal[str values]`, would defintely be a problem.

When would you have a union of strings also include an enum with string values? Do the strings and string values intersect? This is a type I've never run into before. Either way, this is actually one of the easiest versions of this conflict to fix.

I'm happy to resolve some of these issues for you (there's even a [note in our docs](https://jcristharif.com/msgspec/supported-types.html#union-optional) saying so). In particular the following cases would be simple (ish) to fix:

- Unions of `IntEnum` and `Literal[int values]`
- Unions of `Enum` and `Literal[str values]`
- Unions of `datetime`, `date`, and/or `time`.

But if you think having *any* restrictions like this are a no-go for starlite, then I think we'll never reach a point where this issue is resolved. `msgspec` will always be stricter than `pydantic` here. Up to you whether you think it's worth working on reducing these restrictions right now.

**Comment by stints** [comment]
Personally, I like the restrictions and I try to never allow multiple types in an API field request because I want rigid specs.

But why not allow a user at app creation to specify the internal serializer (I assume it's pydantic now and you're planning to switch to msgspec)?  If the choice is possible, could you not explain the choices and a few of the pros and cons of each ie pydantic is a bit more lax but slower while msgspec is more strict but faster.

**Comment by Goldziher** [comment]
> Personally, I like the restrictions and I try to never allow multiple types in an API field request because I want rigid specs.
> 
> But why not allow a user at app creation to specify the internal serializer (I assume it's pydantic now and you're planning to switch to msgspec)? If the choice is possible, could you not explain the choices and a few of the pros and cons of each ie pydantic is a bit more lax but slower while msgspec is more strict but faster.

We use pydantic internally as part of the framework - the project is called starlite: https://github.com/starlite-api/starlite, Im afraid there can be a wide range of types, and they need to be as lax as makes sense.

**Comment by Goldziher** [comment]
> When would you have a union of strings also include an enum with string values? Do the strings and string values intersect? This is a type I've never run into before. Either way, this is actually one of the easiest versions of this conflict to fix.

Its a general rule that whatever is a conceivable use case - will be used. Otherwise there will be little point of having the validations to begin with 😉 . Specifically, here are some examples from our code base itself:

* `Union["Method", Literal["websocket", "asgi"]]` - union of two different literals. 
* `Union[str, "RequestEncodingType"]` - union of string and enum- reason is that the user can either use the `RequestEncodingType` members or a custom string value, both of which are viable values. 
* `Union["MediaType", str]` - same as above.
* `Union[str, bytes]` - value can be either a bytes string or a regular string, and the callee handles both. 
* `Union[str, Path]` - value is either a string or a path object. Path though is also a string type in your system @jcrist.

Number enums and literals follow the same logic, for example consider the interchange of an HTTPStatus enum, with the choice to use literal values or simple ints etc.

A classic one would be the interchange of `Union[int, float]` etc.

I think datetime, time, date etc. are also a common example. Perhaps an API endpoint receives any of these formats. We need to create an OpenAPI spec that has the correct format defined for each one, and to this end we use typing data. Also, the user can expect the query or path parameter (etc.) to be one of these types in the end. 

> I'm happy to resolve some of these issues for you (there's even a [note in our docs](https://jcristharif.com/msgspec/supported-types.html#union-optional) saying so). In particular the following cases would be simple (ish) to fix:
> 
> * Unions of `IntEnum` and `Literal[int values]`
> * Unions of `Enum` and `Literal[str values]`
> * Unions of `datetime`, `date`, and/or `time`.

This boils down to the above - the point for us is not merely performance. Thats nice and certainly the primary reason we decided on this path to begin with, but the other side of this is the utility and DX we offer users. If we go too strict its going to be (a) a huge breaking change we cannot afford, and (b) a miserable experience for most users - especially the more junior ones.

> But if you think having _any_ restrictions like this are a no-go for starlite, then I think we'll never reach a point where this issue is resolved. `msgspec` will always be stricter than `pydantic` here. Up to you whether you think it's worth working on reducing these restrictions right now.

Starlite is an opinionated framework. Having some restrictions is not a problem and is actually a good thing. But having non-negotiable hard strictness on things that are user facing is not gonna cut it. So, its in your field - if you think that msgspec should be very strict and not configurable here, its your decision but indeed that will not work for our use case and we should stop. If you think that there is a middleground or alternative, im game.

**Comment by jcrist** [comment]
> A classic one would be the interchange of `Union[int, float]`

Quick note: `mypy`/`pyright` treat `float` the same as `Union[int, float]`; unions like this are mostly meaningless to type checkers. This union is also supported by msgspec.

> Specifically, here are some examples from our code base itself:
> ...
> If we go too strict its going to be (a) a huge breaking change we cannot afford, and (b) a miserable experience for most users - especially the more junior ones.

I'm not arguing that more complicated union types aren't valid and useful in Python. I am arguing that they are generally unlikely in API specs. All of the examples above aren't for things where `msgspec` would be in the code path, they're for internals of `starlite`. When developing `msgspec` I did a review of a bunch of popular OpenAPI schemas, and none of them would run into issues with the restrictions `msgspec` has. I suspect this is partially an artifact of backend tooling though - in compiled languages (e.g. go) complex field types would be harder to parse and work with in the backend, since much of the tooling wouldn't support them (like go's JSON library).

This isn't saying _all_ API specs don't require these unions, but I'd be surprised if "most" users need them. But I don't know your users, maybe your use case is different.

Anyway, `msgspec` will never support arbitrary unions. We can remove some of the restrictions, but not all of them. It's up to you whether that's satisfactory for your use case; from the above conversation it sounds like it's not.

---

> If you think that there is a middleground or alternative, im game.

Instead of trying to use `msgspec` everywhere, why not only support it for:

- JSON/MessagePack return types (IIUC this already works, as seen by @provinzkraut's nice perf wins in y'all's discord)
- JSON/MessagePack request bodies, when the request body type is a `msgspec.Struct`

This:

- Avoids the need for you to ever dynamically generate a `Struct` type
- Only uses `msgspec` for parsing when the user has opted in by defining a `msgspec.Struct` themselves. Presumably any `msgspec` particularities are fine in that case, since the user made the choice to use `msgspec` here.
- Uses `msgspec` for the things it does best - JSON encoding and decoding. Using it for parsing other bits might have some perf benefit, but the JSON encoding/decoding aspect is really what it does best.

You'd still need to split out the body parsing from the query/header/cookie/... models (as I suggested in https://github.com/jcrist/msgspec/issues/301#issuecomment-1434842236) to let `msgspec` directly decode into the specified type. But (from my non-starlite-contributor view :)) this seems like much less work than going all-in on msgspec. Just my 2c.

**Comment by Goldziher** [comment]
> > A classic one would be the interchange of `Union[int, float]`
> 
> Quick note: `mypy`/`pyright` treat `float` the same as `Union[int, float]`; unions like this are mostly meaningless to type checkers. This union is also supported by msgspec.
> 
> > Specifically, here are some examples from our code base itself:
> > ...
> > If we go too strict its going to be (a) a huge breaking change we cannot afford, and (b) a miserable experience for most users - especially the more junior ones.
> 
> I'm not arguing that more complicated union types aren't valid and useful in Python. I am arguing that they are generally unlikely in API specs. All of the examples above aren't for things where `msgspec` would be in the code path, they're for internals of `starlite`. When developing `msgspec` I did a review of a bunch of popular OpenAPI schemas, and none of them would run into issues with the restrictions `msgspec` has. I suspect this is partially an artifact of backend tooling though - in compiled languages (e.g. go) complex field types would be harder to parse and work with in the backend, since much of the tooling wouldn't support them (like go's JSON library).
> 
> This isn't saying _all_ API specs don't require these unions, but I'd be surprised if "most" users need them. But I don't know your users, maybe your use case is different.
> 
> Anyway, `msgspec` will never support arbitrary unions. We can remove some of the restrictions, but not all of them. It's up to you whether that's satisfactory for your use case; from the above conversation it sounds like it's not.
> 
> > If you think that there is a middleground or alternative, im game.
> 
> Instead of trying to use `msgspec` everywhere, why not only support it for:
> 
> * JSON/MessagePack return types (IIUC this already works, as seen by @provinzkraut's nice perf wins in y'all's discord)
> * JSON/MessagePack request bodies, when the request body type is a `msgspec.Struct`
> 
> This:
> 
> * Avoids the need for you to ever dynamically generate a `Struct` type
> * Only uses `msgspec` for parsing when the user has opted in by defining a `msgspec.Struct` themselves. Presumably any `msgspec` particularities are fine in that case, since the user made the choice to use `msgspec` here.
> * Uses `msgspec` for the things it does best - JSON encoding and decoding. Using it for parsing other bits might have some perf benefit, but the JSON encoding/decoding aspect is really what it does best.
> 
> You'd still need to split out the body parsing from the query/header/cookie/... models (as I suggested in [#301 (comment)](https://github.com/jcrist/msgspec/issues/301#issuecomment-1434842236)) to let `msgspec` directly decode into the specified type. But (from my non-starlite-contributor view :)) this seems like much less work than going all-in on msgspec. Just my 2c.

Thanks! Yes, we decided not to proceed with integration of msgspec in our internals since it doesn't fit. We will see about supporting msgspect request bodies.

**Comment by jcrist** [comment]
:+1: I'm going to close this issue then.
