### ISSUE TITLE
Recursive definitions

### ISSUE THREAD

**Issue by limx0** [jcrist/msgspec#329]
### Description

Hi @jcrist, thanks again for this excellent little library. 

I've got some JSON data that has nested definitions, something like:

``` python
class Value(msgspec.Struct):
    value: int
    
class Group(msgspec.Struct):
    name: str
    children: list[Group | Value]
```

and the data looks something like: 

```JSON
{
  "type": "GROUP",
  "name": "top_group",
  "children": [
    {
      "type": "VALUE",
      "name": "top_value"
    },
    {
      "type": "GROUP",
      "name": "nested_group",
      "children": [
        {
          "type": "VALUE",
          "name": "nested_value"
        }
      ]
    }
  ]
}
```

I wonder is there a way to define this type of recursive relationship in msgspec? I checked the docs + issues but don't think this has been asked before (apologies if it has).

**Comment by jcrist** [comment]
Hi @limx0. Yes, these are supported. The issue here is one of forward declarations (how can you reference the `Group` type within `Group`). This isn't specific to `msgspec`, it's a generic python type annotation issues. You might find [this mypy docs section](https://mypy.readthedocs.io/en/stable/runtime_troubles.html#class-name-forward-references) helpful.

In short, you have two options:

- Add a `from __future__ import annotations` call at the top of your file. This will disable evaluation of the type annotations at import time, so when they're finally evaluated all types are defined in the namespace.
- Add quotes around "Group" inside the definition of `Group`. This delays only that evaluation.

I had to modify your JSON a bit since it didn't match the schema, but the following script runs for me:

```python
from __future__ import annotations

import msgspec


class Value(msgspec.Struct, tag=str.upper):
    value: int
    name: str
    

class Group(msgspec.Struct, tag=str.upper):
    name: str
    children: list[Group | Value]


msg = """
{
  "type": "GROUP",
  "name": "top_group",
  "children": [
    {
      "type": "VALUE",
      "name": "top_value",
      "value": 1
    },
    {
      "type": "GROUP",
      "name": "nested_group",
      "children": [
        {
          "type": "VALUE",
          "name": "nested_value",
          "value": 2
        }
      ]
    }
  ]
}
"""

print(msgspec.json.decode(msg, type=Group))
```

**Comment by jcrist** [comment]
Since this is a general Python type hinting issue, I hadn't thought to document this specifically in the `msgspec` docs. Do you think documenting something like this would be worth it, and if so where in our docs would you put this information?

**Comment by limx0** [comment]
Thanks for the quick response! I knew it was a typing issue but wasn't sure of the proper term or how to solve it (thanks for the mypy link, I will have a read). I did try the quotes method but must've had some other bug in my code. Both of those options above are working as expected now, so the issue can be closed.

Regarding documentation, I think it would definitely be worthwhile mentioning as msgspec makes strong use of type annotations. The barrier to using msgspec may be lower than that of some of the newer typing features, so potentially flagging some of these (only as they related to JSON data you see in the wild) would be worthwhile IMO. 
 
I personally was looking for it in the `structs` page, which seems to be broken down by the various ways to handle different JSON data in msgspec, this seems like a reasonable place to put something if you see fit? (somewhere around tagged unions or arrays)
