### ISSUE TITLE
doc are built off main leading to confusion

### ISSUE THREAD

**Issue by kingarrrt** [jcrist/msgspec#337]
### Description

The docs you publish at https://jcristharif.com/msgspec/ are built from the main branch. This makes things confusing when they refer to things not available in the latest release.

Great project, many thanks.

**Comment by jcrist** [comment]
Historically there haven't been a ton of breaking changes/new features in the docs, so a week or two lag hasn't been a big deal. If this is a big enough problem, we could either hold off publishing docs until a release, or look into versioning our docs.

Out of curiosity, what unreleased feature were you trying to use that led to this issue?

**Comment by kingarrrt** [comment]
The `dict` argumnent to `msgspec.Struct` ( #331) .

**Comment by jcrist** [comment]
Thanks for opening this issue. I'm a bit torn on whether we want to hold off publishing docs until a release. I frequently make small changes to the docs between releases to clarify user questions - in this case it would be nice if these changes were immediately available. But when large features are added I can see having the docs up before they're released being confusing. However, historically we've had a pretty short release cadence, minimizing the amount of time a user could run into this issue.

Since this is the first time this has come up, I'm going to close this for now without making a process change. If it comes up again I'll rethink how we publish docs.
