### ISSUE TITLE
Concrete fields for tagged unions.

### ISSUE THREAD

**Issue by provinzkraut** [jcrist/msgspec#338]
### Description

The current implementation of tagged unions does not treat the tag field (i.e. the discriminator) as a proper field of the actual struct. This insufficiently models real world usage where more often than not, the field of a message you want to discriminate based on is a proper part of the schema, that you'd also want to represent with a field on the struct.

An example:

Given a message with the schema 

```json
[
    {"type": "foo_event", "id": "12345", "some_field": "some_value"},
    {"type": "bar_event", "id": "67891", "some_other_field": "some_other_value"}
]
```

Which would be modeled by these structs

```python
class BaseEvent(Struct):
    type: Literal["foo_event", "bar_event"]
    id: str


class FooEvent(BaseEvent):
    type: Literal["foo_event"]
    some_field: str


class BarEvent(BaseEvent):
    type: Literal["bar_event"]
    some_other_field: str
```

Ideally, you'd then be able to decode the message using something like `decode(...,type=list[FooEvent | BarEvent])`.

The current implementation requires structs to be defined like this

```python
class BaseEvent(Struct):
    id: str


class FooEvent(BaseEvent, tag_field="type", tag="foo_event"):
    some_field: str


class BarEvent(BaseEvent, tag_field="type", tag="bar_event"):
    some_other_field: str
```

which does not make the `type` field available on the struct objects.

<hr>

**Additional context**

This is currently supported by Pydantic with [discriminated unions](https://docs.pydantic.dev/usage/types/#discriminated-unions-aka-tagged-unions)

**Comment by jcrist** [comment]
We explicitly chose not to follow that pattern, mostly because I find it nonintuitive and verbose to write out. A few problems with it:

- Sometimes the tag field isn't a valid python identifier (I've seen `"$type"`, `"class"`, ...). This makes it harder to have the tag as a true attribute on the object.
- Making the tag a true field means it can be an argument to the struct constructor. Since it's a literal with only one value, you probably want to make it an optional field, which further duplicates the information you need to write:

    ```python
    class BarEvent(Struct):
        type: Literal["bar_event"] = "bar_event"  # so verbose
    ```

- Making it a true field on the struct makes it harder to know what field is the discriminator when decoding. Right now this is stored on the struct itself, which feels like the proper place to me, rather than putting it somewhere else on the union.
- Making it a true field is also less efficient, since every instance of that struct will needlessly store a copy of the same data (taking up a pointer space).

In my experience, the tag is an artifact of serialization/deserialization, and not something that needs to be accessed on the struct itself at runtime. If they're all different types, isn't determining the output type what `isinstance` is for?

```python
# Instead of
if event.type == "bar_event":
    ...

# you'd do
if isinstance(event, BarEvent):
    ...
```

If you really want a `type` property on the struct, you can also do that with a classvar:

```python
class BaseEvent(Struct):
    type: ClassVar[str]
    id: str


class FooEvent(BaseEvent, tag="foo_event"):
    type = "foo_event"
    some_field: str


class BarEvent(BaseEvent, tag="bar_event"):
    type = "bar_event"
    some_other_field: str

event = BarEvent(id="123", some_other_field="foo")
assert event.type == "bar_event"
```

This has the benefit of keeping the tag & value off struct instances (saving a bit of CPU and memory), and keeping them out of the struct constructor where they'd never be manually set anyway.

If that's insufficient for your use case, then I'd need a better example/explanation of what's lacking here for your use case.

**Comment by provinzkraut** [comment]
> mostly because I find it nonintuitive and verbose to write out

No arguments there, it's not the most elegant, but unfortunately, I don't see any other way.

> Sometimes the tag field isn't a valid python identifier

True, but msgspec could just opt to not support those as concrete attributes then.

> Making the tag a true field means it can be an argument to the struct constructor. Since it's a literal with only one value, you probably want to make it an optional field, which further duplicates the information you need to write

Yes, that is a downside, but one I'd be willing to accept.

> Making it a true field on the struct makes it harder to know what field is the discriminator when decoding. Right now this is stored on the struct itself, which feels like the proper place to me, rather than putting it somewhere else on the union.

The information which field is the discriminator could still live on the struct. The way I imagine it working is basically identical to how it is now, with the only difference being that you can (optionally) define the field on the struct.

> Making it a true field is also less efficient

Probably, but I can't imagine the impact of this being huge. Especially considering that with my proposal it would be entirely optional, it's definitely something I'd accept as a downside.

> In my experience, the tag is an artifact of serialization/deserialization, and not something that needs to be accessed on the struct itself at runtime

That's where I disagree. The example I showed was a simplified API response, used in an API client that I'm thinking of migrating from Pydantic to msgspec. The `type` field is, for better or worse, being used downstream in a lot of places. You might feel that it's just for ser/de, but within the application this is being used it's not just that.

> If you really want a type property on the struct, you can also do that with a classvar:

Well yes, I could do that, but then I couldn't easily deserialize the incoming message based on the `type` into the appropriate structs. I'd have to do something like

```python
event_types = {"foo_event": FooEvent, "bar_event": BarEvent}

data = [from_builtins(event_types[event["type"]]) for event in decode(...)]
```

which is not only quite cumbersome, but I'd also lose validation on the initial load, and the benefit of doing parsing / validation in one step.

**Comment by jcrist** [comment]
Thanks for the context here. I'm going to rephrase your ask here as:

"It would be nice to be able to access the `type` field of these structs as an attribute on an instance named `type`"

rather than anything about them being a proper field on the struct (or using the same spelling as pydantic). Downstream consumers of these objects wouldn't see a change then.

If that's a valid interpretation, then you're in luck - there's several ways this can be handled today without changes to `msgspec`.

### Using a ClassVar

The first way is the way I showed above. This works exactly the same as before (no need for using `from_builtins` or anything like that). The `type` attribute just happens to live on the *class* rather than the *instance*.

A working example:

```python
from typing import Literal, ClassVar

import msgspec

EventType = Literal["foo_event", "bar_event"]


class BaseEvent(msgspec.Struct):
    type: ClassVar[EventType]
    id: str


class FooEvent(BaseEvent, tag="foo_event"):
    type = "foo_event"
    some_field: str


class BarEvent(BaseEvent, tag="bar_event"):
    type = "bar_event"
    some_other_field: str


data = """
[
    {"type": "foo_event", "id": "abc", "some_field": "fizz"},
    {"type": "bar_event", "id": "def", "some_other_field": "buzz"}
]
"""

events = msgspec.json.decode(data, type=list[FooEvent | BarEvent])
for event in events:
    print(f"{event=}")
    print(f"{event.type=}")

# event=FooEvent(id='abc', some_field='fizz')
# event.type='foo_event'
# event=BarEvent(id='def', some_other_field='buzz')
# event.type='bar_event'
```

### Using a property

I like the solution above because it's low tech. No magic needed, the `type` is an attribute stored on the class. The downside is that it requires a bit of repetition of the tag value.

If the repetition bothers you, you could make `type` a `property` instead. This would add a mild runtime cost, but wouldn't require duplicating the tag value twice. Note that this solution requires a feature that hasn't been released yet (hoping to release next week).


```python
from typing import Literal

import msgspec

EventType = Literal["foo_event", "bar_event"]


class BaseEvent(msgspec.Struct):
    id: str

    @property
    def type(self) -> EventType:
        return self.__struct_config__.tag


class FooEvent(BaseEvent, tag="foo_event"):
    some_field: str


class BarEvent(BaseEvent, tag="bar_event"):
    some_other_field: str


data = """
[
    {"type": "foo_event", "id": "abc", "some_field": "fizz"},
    {"type": "bar_event", "id": "def", "some_other_field": "buzz"}
]
"""

events = msgspec.json.decode(data, type=list[FooEvent | BarEvent])
for event in events:
    print(f"{event=}")
    print(f"{event.type=}")

# event=FooEvent(id='abc', some_field='fizz')
# event.type='foo_event'
# event=BarEvent(id='def', some_other_field='buzz')
# event.type='bar_event'
```


Would either of the above solutions be sufficient for your needs?

**Comment by provinzkraut** [comment]
@jcrist Thanks a lot, it seems like this sufficiently covers my use case!

I have a question though, since from reading the docs it's not obvious to me: How does msgspec determine that the `type` value of the `type` class var is to be used for the tag simply by specifying its value using `tag=...`? I would have thought that I'd need to also set `tag_field="type"`.
