### ISSUE TITLE
Losslessly represent omitted fields

### ISSUE THREAD

**Issue by SyntaxColoring** [jcrist/msgspec#344]
# Description

I sometimes have JSON objects where the presence or absence of a field is semantically distinct from whether that field's value is `null`.

In keeping with `msgspec`'s principles of strictness and correctness, I'd like for the library to be able to losslessly and reversibly encode and decode these objects.

# Example use case

Suppose you have a database of software bugs. Each bug has a `title`, and, optionally, a single `assignee`.

You want to use JSON to represent search filters.

This filter would mean "find all issues titled 'App crashes' that are assigned to `@JohnDoe`":

```json
{
    "title": "App crashes"
    "assignee": "@JohnDoe"
}
```

And this would mean "find all issues titled 'App crashes' that **don't have an assignee**":

```json
{
    "title": "App crashes"
    "assignee": null
}
```

And this would mean "find all issues titled 'App crashes' **regardless of assignee**":

```json
{
    "title": "App crashes"
}
```

In JSON Schema, I would represent this like this:

```json
{
    "$ref": "#/$defs/SearchFilter",
    "$defs": {
        "SearchFilter": {
            "title": "SearchFilter",
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "assignee": {
                    "anyOf": [
                        { "type": "string" },
                        { "type": "null" }
                    ]
                }
            }
            "required": []
        }
    }
}
```

# Proposed API design

Using `msgspec`, I would want to implement the example above something like this:

```python
class SearchFilter(msgspec.Struct):
    # OMITTED and OMITTED_TYPE do not exist today.
    title: str | msgspec.OMITTED_TYPE = msgspec.OMITTED
    assignee: str | None | msgspec.OMITTED_TYPE = msgspec.OMITTED


def filter(all_bugs: list[Bug], filter: SearchFilter) -> list[Bug]:
    def matches_filter(bug: Bug) -> bool:
        title_matches = filter.title == msgspec.OMITTED or filter.title == bug.title
        assignee_matches = filter.assignee == msgspec.OMITTED or filter.assignee == bug.assignee
        return title_matches and assignee_matches
    return [bug for bug in all_bugs if matches_filter(bug)]
```

* Two new symbols are added to `msgspec`: `OMITTED` and `OMITTED_TYPE`.
  * `OMITTED` is a unique sentinel value, distinct from `None`.
  * `OMITTED_TYPE` is the type of `OMITTED`, probably an alias of `typing.Literal[OMITTED]`.
  * Perhaps values of `OMITTED` evaluate to falsey, like `None` does.
* When `encode()` encounters a value of `OMITTED`, it omits the entire key-value pair from the output.
* The `decode()` behavior is unchanged. When it decodes a message that has a certain field missing, it returns that field's default value. In this case, that value can happen to be the sentinel value `OMITTED`.

# Prior art in other libraries

## [PEP 655](https://peps.python.org/pep-0655/)

[PEP 655](https://peps.python.org/pep-0655/) discusses the same problem for `TypedDict`s.

They solve it in a different way. Instead of having a special sentinel value like I'm proposing, they introduce the wrapping types `typing.Required[T]` and `typing.NotRequired[T]`. (These appear to be pass-throughs to `T` at run time. I guess you're supposed to use the `in` operator to gate any potentially unsafe accesses, but [mypy doesn't enforce this today](https://github.com/python/mypy/issues/12094).)

They also explicitly reject the name "omittable."

It feels to me like a lot of their arguments don't make sense when applied to `msgspec.Struct`s, as opposed to `dict`s. But I haven't spent the time to try these things out, or to read the mailing lists and dig into their thinking. Maybe they're right.

## Pydantic

Pydantic has historically badly conflated these concepts. [Planned changes for v2.0](https://docs.pydantic.dev/blog/pydantic-v2/#required-vs-nullable-cleanup) look like they'll bring Pydantic to parity with `msgspec` as it exists today, but they won't address the problem I'm describing here.

**Comment by jcrist** [comment]
Thanks for opening this, this seems like a well thought out feature, and shouldn't be too hard to implement. I think the only open question here would be the naming.

I don't like using the name `Omitted` here, since it may conflict with how we spell omitted fields whenever that's implemented (#199). My initial instinct is to use the name `UNSET`. This would  unfortunately require a breaking change for existing internal consumers of the `msgspec.UNSET` sentinel, but I doubt anyone is using it directly outside `msgspec` since it was only recently added, and is a fringe API.

For typing, we could do something like the following to make spelling these fields easier:

```python
# This type annotation helper would be in `msgspec`:
# MaybeUnset = Union[T, UnsetType]

from msgspec import Struct, MaybeUnset, UNSET

class SearchFilter(Struct):
    # OMITTED and OMITTED_TYPE do not exist today.
    title: MaybeUnset[str] = UNSET
    assignee: MaybeUnset[str | None] = UNSET
```

I don't love the name `MaybeUnset`, but `Unsettable` sounds more like a field that can never be set.

Alternatively we could use `UNDEFINED` and `MaybeUndefined` (or some other equivalent name) for the same concepts. This may better mirror javascript semantics, but I'm not sure if a Python programmer would find the meaning/usage of `UNDEFINED` here as clear.

Thoughts?

**Comment by jcrist** [comment]
The more I think about this, the more I like using "undefined" here. This would also let us mirror `JSON.stringify` behavior, where an `undefined` in a non-object-value location is encoded as `null` instead of erroring (so `[1, undefined]` would encode as `[1, null]`).

Still not sure about the singleton/type naming/casing. Thoughts here would be very welcome.

Possible singleton names: `msgspec.UNDEFINED`, `msgspec.undefined`, `msgspec.Undefined`, ?

Possible type names: `msgspec.UndefinedType`, `msgspec.Undefined`, ?


```python
# Just playing around with spellings here
class Example(msgspec.Struct):
    field_1: str | msgspec.UndefinedType = msgspec.UNDEFINED
    field_2: str | msgspec.Undefined = msgspec.undefined
    field_3: str | msgspec.UndefinedType = msgspec.Undefined
```

**Comment by jcrist** [comment]
I've pushed up #350 to fix this. The semantics are pretty much what you describe above, with the singleton named `msgspec.UNSET` and the type named `msgspec.UnsetType`. If you have some time, I'd appreciate a once over on the docs in that PR to make sure usage makes sense to you. Thanks!
