### ISSUE TITLE
Accept JSON key string in Structs with periods ('.') in them.

### ISSUE THREAD

**Issue by colinponce** [jcrist/msgspec#353]
### Description

In cybersecurity, a popular tool is [Zeek](https://zeek.org/), which produces logs, often in JSON format, of network traffic that can be analyzed for suspicious behavior. These logs can be very long, making msgspec an excellent tool to help in analyzing them. A typical log entry might look like this:
```
{"ts":1678939315.426108,"uid":"Skv23B19aqxd0uroYb","id.orig_h":"1.2.3.4","id.orig_p":47234,"id.resp_h":"5.6.7.8","id.resp_p":9961,"proto":"tcp","duration":2.0011210441589355,"orig_bytes":0,"resp_bytes":0,"conn_state":"S0","local_orig":true,"local_resp":false,"missed_bytes":0,"history":"S","orig_pkts":2,"orig_ip_bytes":128,"resp_pkts":0,"resp_ip_bytes":0}
```

The keys and value formats are standardized. As you can see, some of the keys have periods in them, in particular, `id.orig_h`, `id.orig_p`, `id.resp_h`, and `,id.resp_p`, which give the local and remote IP and port numbers involved in the connection. 

When not passing a particular msgspec Struct, msgspec parses this just fine, but we lose out on the speed benefits of specifying a Struct. I have not been able to find a way to specify a Struct that has a period in the key.

Trying to create a typical Struct, like
```
class ConnEntry(msgspec.Struct):
    ts: float
    uid: str
    id.orig_h: str
```
fails silently; the resulting dictionary has "ts" and "uid" keys but no "id.orig_h" key.

Trying to do this at runtime, like
```
        ConnEntry = msgspec.defstruct("ConnEntry", [("ts", float), ("uid", str), ("id.orig_h", str)])
```
or, trying to escape the period,
```
        ConnEntry = msgspec.defstruct("ConnEntry", [("ts", float), ("uid", str), ("id\.orig_h", str)])
```
results in the error `TypeError: __slots__ must be identifiers`.

Trying to split it into multiple Structs in a way that matches the accessor syntax,
```
class IDOrigH(msgspec.Struct):
    orig_h: str

class ConnEntry(msgspec.Struct):
    ts: float
    uid: str
    id: IDOrigH
```
results in the error "msgspec.ValidationError: Object missing required field `id` - at `$[0]`".

In retrospect all these errors are pretty unsurprising. Is there a way to specify a `Struct` with period characters in the keys? If not, is it possible to add such a feature?

**Comment by provinzkraut** [comment]
> fails silently

This is just a coincidence, because you're using `id`, which is a built-in function. If you try it with a random name, it will not fail silently:

```python
class Test(msgspec.Struct):
  foo.bar: str
```

this is not related to msgspec and you'll get the same error by just doing

```python
foo.bar: str
```

As for your main question, would [field renaming](https://jcristharif.com/msgspec/structs.html#renaming-field-names) solve your issue?

```python
import msgspec

class ConnEntry(msgspec.Struct, rename={"id_orig_h": "id.orig_h"}):
    ts: float
    uid: str
    id_orig_h: str
```

**Comment by jcrist** [comment]
Thanks for opening this. Yes this feature is currently supported, through the `rename` config option in the struct definition ([docs](https://jcristharif.com/msgspec/structs.html#renaming-field-names)).

You can't use field names with a period in them, since names like that aren't valid python identifiers. Instead you want to rename the fields to something valid in python (e.g. `id_orig_h`), but note that the serialized name is different (e.g. `id.orig_h`).

Here's a working example to get you started:

```python
import msgspec

msg = (
    b'{"ts":1678939315.426108,"uid":"Skv23B19aqxd0uroYb",'
    b'"id.orig_h":"1.2.3.4","id.orig_p":47234,"id.resp_h":"5.6.7.8",'
    b'"id.resp_p":9961,"proto":"tcp","duration":2.0011210441589355,'
    b'"orig_bytes":0,"resp_bytes":0,"conn_state":"S0","local_orig":true,'
    b'"local_resp":false,"missed_bytes":0,"history":"S","orig_pkts":2,'
    b'"orig_ip_bytes":128,"resp_pkts":0,"resp_ip_bytes":0}'
)

class ConnEntry(
    msgspec.Struct,
    rename={"id_orig_h": "id.orig_h"}
):
    ts: float
    uid: str
    id_orig_h: str


x = msgspec.json.decode(msg, type=ConnEntry)
print(x)
#> ConnEntry(ts=1678939315.426108, uid='Skv23B19aqxd0uroYb', id_orig_h='1.2.3.4')
```

You only need to pass in names that need renaming to the `rename` kwarg, any fields not present in the mapping will use their original name.

Currently this configuration is only available as a config option on the class itself. In the future I plan to add a `name` option (there may be a better name for this kwarg) in `msgspec.field` so you could instead write this as:

```python
class ConnEntry(msgspec.Struct):
    ts: float
    uid: str
    id_orig_h: str = msgspec.field(name="id.orig_h")
```

In some cases this would be nicer, as it keeps configuration related to a specific field closer together.

Does that answer your question?

**Comment by jcrist** [comment]
Oops, sorry for the duplicate response, I was typing while @provinzkraut was answering and missed they'd already replied :).

**Comment by colinponce** [comment]
Thank you for the response! It makes sense that these errors were due to them not being valid identifiers.

As to your suggestion, yes! That approach seems to solve the problem. A 

```
renaming_dict = {"id_orig_h": "id.orig_h",
                   "id_orig_p": "id.orig_p",
                   "id_resp_h": "id.resp_h",
                   "id_resp_p": "id.resp_p"}

class ConnEntry(msgspec.Struct, rename=renaming_dict):
    ts: float
    uid: str
    id_orig_h: str
    id_orig_p: int
    id_resp_h: str
    id_resp_p: int
```

results in outputs that look like
```
ConnEntry(ts=1678939315.426108, uid='Skv2HBf9mdxB3u5oYb', id_orig_h='1.2.3.4', id_orig_p=47234, id_resp_h='6.7.8.9', id_resp_p=9961)
```

Which is exactly what I am looking for. Thank you!

**Comment by colinponce** [comment]
@jcrist @provinzkraut Thanks to both of you for your prompt and helpful responses. I appreciate it!
