### ISSUE TITLE
[Question] Generate a Struct automatically from JSONSchema?

### ISSUE THREAD

**Issue by stevesimmons** [jcrist/msgspec#390]
### Description

Are there any ways to automatically generate a typed Struct from a JSONSchema definition? This is the reverse of generating JSONSchema for a given Struct.

This is similar to https://github.com/koxudaxi/datamodel-code-generator, which can generate code for Pydantic models and standard Python dataclasses.

I guess one way to achieve this would be modifying the datamodel-code-generator's code generation stage to emit Struct format.

Are there any other solutions anyone knows of?

Thanks!
Stephen

**Comment by jcrist** [comment]
Hi, thanks for opening this. A feature like this would be better handled by an upstream tool like `datamodel-code-generator`. As such, I've opened https://github.com/koxudaxi/datamodel-code-generator/issues/1278.

Note that `msgspec` natively supports `dataclasses` as well as our own `msgspec.Struct` types. The existing `dataclasses` support in `datamodel-code-generator` *may* already work fine with `msgspec`, although using a `msgspec.Struct` class instead would certainly be more efficient. If you're interested, have it generate `dataclasses` and try using them with `msgspec` - things may *just work*. Let me know how it goes.

Since this work is non-trivial and IMO should happen upstream in `datamodel-code-generator`, I'm going to close this issue here for now.

**Comment by dhirschfeld** [comment]
Support has been added upstream:
https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.22.0
