### ISSUE TITLE
Structs are not pickleable with cloudpickle

### ISSUE THREAD

**Issue by Chumper** [jcrist/msgspec#394]
### Description

First of: Great work with the library, it solves a lot of my problems passing data between different processes.

## My Problem: 
Assume the following script (with `msgspec` and `cloudpickle` installed:
```python
from msgspec import Struct
import cloudpickle

class MyStruct(Struct):
    a: str

data = cloudpickle.dumps(MyStruct(a="hello"))

# imagine sending this data to another process

myclass = cloudpickle.loads(data)
# errors with: cannot set '__new__' attribute of immutable type 'msgspec._core.StructMeta'

print(myclass)
```

This script errors out because the `MyStruct` class is pickleable but not decodeable.

## Why do I need this?

I am using `msgspec` to experiment with a distributed system, `msgspec` is used for message passing between different processes.
To send the class to a different process I am using `cloudpickle` to pickle a class (which is using the Struct as message).
The other process then tries to dump the class and initialize it.

Alternatives for me would be to send only the class name and the arguments and load the class on the other process and invoke it with the args, but I am trying to make it as easy as possible for the end user to use my library.

Is this something that can be fixed/changed or should I find an alternative way to achieve the result?

**Comment by jcrist** [comment]
Hi, apologies for the delayed  response here. A bit of clarification here (you may know this already):

`msgspec.Struct` instances are pickleable by default, both using the standard `pickle` module as well as the extended `cloudpickle` module.

```python
# mymodule.py
import msgspec

class Point(msgspec.Struct):
    x: int
    y: int
```

```python
In [1]: import pickle, cloudpickle

In [2]: from mymodule import Point

In [3]: pickle.loads(pickle.dumps(Point(1, 2)))
Out[3]: Point(x=1, y=2)

In [4]: cloudpickle.loads(cloudpickle.dumps(Point(1, 2)))
Out[4]: Point(x=1, y=2)
```

When a `Struct` (or any normal class instance) is pickled, a reference to the class is included in the serialized message. For classes defined in modules, this is generally just an import path string, pointing to where they can be loaded from.

```python
In [5]: x = Point(1, 2)

In [6]: x.__reduce__()  # Use reduce to see the objects being sent as part of pickling
Out[6]: (mymodule.Point, (1, 2))

In [7]: pickle.dumps(Point(1, 2))  # Pickling an instance includes the full import path to its class (`mymodule.Point`)
Out[7]: b'\x80\x04\x95\x1e\x00\x00\x00\x00\x00\x00\x00\x8c\x08mymodule\x94\x8c\x05Point\x94\x93\x94K\x01K\x02\x86\x94R\x94.'
```

*However*, classes defined dynamically or as part of the `__main__` namespace won't generally be pickleable, since they may not be available in the receiving process's `__main__` namespace. One place this comes up is classes defined in a script that is then run as `python myscript.py`.

```python
# myscript.py
import msgspec
import pickle

class Point(msgspec.Struct):
    x: int
    y: int

print(Point.__module__)
#> '__main__'

print(pickle.dumps(Point(1, 2)))  # contains a reference to `__main__.Point`
#> b'\x80\x04\x95\x1e\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x05Point\x94\x93\x94K\x01K\x02\x86\x94R\x94.'
```

This is one of the problems that `cloudpickle` stries to solve. When it encounters a class defined in the `__main__` module, it serializes the class *not* as a reference using its import path, but as a collection of objects that can then be used to reconstruct the class on the receiving side (similar to if you serialized the source code and used `exec` to redefine the class in the receiving process).

`cloudpickle` has to do some deep python magic to make this work, and makes a bunch of (mostly reasonable) assumptions about how a class may be defined. Unfortunately these assumptions hold true for `msgspec.Struct` types, since they have a different memory layout than standard python classes. I don't see a good way to work around this without requiring a bunch of changes to msgspec's internals. You could probably work around this by subclassing `cloudpickle.CloudPickler` and overriding `reducer_override` to special case `msgspec.Struct` classes that are defined in the `__main__` namespace (you might use `msgpsec.defstruct` to rebuild these, rather than the default classes). But that seems like a lot of work.

A better solution is to avoid defining `msgspec.Struct` classes in the main namespace, and instead define them in submodules that have a valid import path. Instances will then be pickleable just like any other type.

**Comment by Chumper** [comment]
Thanks for the detailed explanation! That makes a lot of sense.
My reasoning for doing it the "script" way is because with that I can provide a simple example for the end users to run, similar to the pydantic docs.
I agree that it would not make sense to define the message class in the main method otherwise.

In this case I will rewrite the examples to indicate that messages need to be defined in a separate module (which is the normal way anyway, except in the examples)

**Comment by akotlar** [comment]
I think I ran into this "problem" as well, but with a somewhat different, and confusing error. @jcrist could you comment on whether the issue I saw is due to the same __main__ module issue?

`buteError: type object 'StructMeta' has no attribute '__struct_fields__'`

Stack trace:

```
[36m(handle_job pid=572324)[0m Connecting to existing Ray cluster at address: 10.98.135.15:6379...
[36m(handle_job pid=572324)[0m Calling ray.init() again after it has already been called.
[36m(handle_job pid=572324)[0m type object 'StructMeta' has no attribute '__struct_fields__'
[36m(handle_job pid=572324)[0m Traceback (most recent call last):
[36m(handle_job pid=572324)[0m   File "/home/ubuntu/miniconda3/envs/bystro/lib/python3.11/site-packages/ray/_private/serialization.py", line 412, in deserialize_objects
[36m(handle_job pid=572324)[0m     obj = self._deserialize_object(data, metadata, object_ref)
[36m(handle_job pid=572324)[0m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(handle_job pid=572324)[0m   File "/home/ubuntu/miniconda3/envs/bystro/lib/python3.11/site-packages/ray/_private/serialization.py", line 271, in _deserialize_object
[36m(handle_job pid=572324)[0m     return self._deserialize_msgpack_data(data, metadata_fields)
[36m(handle_job pid=572324)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(handle_job pid=572324)[0m   File "/home/ubuntu/miniconda3/envs/bystro/lib/python3.11/site-packages/ray/_private/serialization.py", line 226, in _deserialize_msgpack_data
[36m(handle_job pid=572324)[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)
[36m(handle_job pid=572324)[0m                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(handle_job pid=572324)[0m   File "/home/ubuntu/miniconda3/envs/bystro/lib/python3.11/site-packages/ray/_private/serialization.py", line 216, in _deserialize_pickle5_data
[36m(handle_job pid=572324)[0m     obj = pickle.loads(in_band)
[36m(handle_job pid=572324)[0m           ^^^^^^^^^^^^^^^^^^^^^
[36m(handle_job pid=572324)[0m AttributeError: type object 'StructMeta' has no attribute '__struct_fields__'
```
