### ISSUE TITLE
Support `NotRequired` in `TypedDict` when `__future__.annotations` is enabled

### ISSUE THREAD

**Issue by guacs** [jcrist/msgspec#404]
### Description

[PEP 655](https://peps.python.org/pep-0655/) adds support for `NotRequired` and `Required`. Currently it seems `msgspec` doesn't support it, but it does support `total=False` when defining a `TypedDict`. Is this something that can be supported?

I actually encountered this when I was trying to create a typed dictionary for specifying the values that can be updated in a specific table in Postgres. That is, whichever values are provided would be updated. Initially I had something like this:

```python

class UpdateRequest(TypedDict):

    id: str
    some_value: NotRequired[int]
    another_value: NotRequired[str]
    ...
```
This is what the body of the request from the client was going to be. I refactored this to make it work with msgpec by doing the following:

```python

class UpdateEntity(TypedDict, total=False):

    some_value: int
    another_value: str
    ...

class UpdateRequest(TypedDict):

     id: str
     update_details: UpdateEntity
```

**Comment by jcrist** [comment]
Thanks for opening this issue. `NotRequired`/`Required` _do_ work, but only if you don't use `from __future__ import annotations`. This is due to an upstream bug in CPython (see https://github.com/python/typing_extensions/issues/55 and https://github.com/python/cpython/issues/97727).

You can work around this issue for now by doing as you've done above, or avoiding the `from __future__ import annotations` import.

In the long run I think we'll move to parsing the `Required`/`NotRequired` types directly ourselves, rather than relying on the current buggy `typing.TypedDict` internals to do it for us.

**Comment by jcrist** [comment]
No problem! I'm going to keep this open for now to remind me to update our logic to manually handle `Required`/`NotRequired` rather than relying on `TypedDict` to do it for us.

**Comment by guacs** [comment]
Yeah sure that's a good idea.
