### ISSUE TITLE
Specifying an optional_default instead of UNSET

### ISSUE THREAD

**Issue by ml31415** [jcrist/msgspec#406]
### Description

I have a lot of code making heavy use of `typing.Optional` like:

```python
class SomeClass(msgspec.Struct):
    field1: Optional[...] = None
    field2: Optional[...] = None
    field3: Optional[...] = None
```
Specifying `None` all the time feels super redundant, given that I already specified `Optional[...]`. Ideally, I'd wish for something like:

```python
class SomeClass(msgspec.Struct, optional_default=None):
    field1: Optional[...]
    field2: Optional[...]
    field3: Optional[...]
```    
If that value would be inherited, even better. That would make a lot of my code way less verbose. Of course, setting an explicit other default should still work:

```python
class SomeClass(msgspec.Struct, optional_default=None):
    field1: Optional[...]
    field2: Optional[...] = "not there"
```
Another option to implement this functionality might be, to have a `default=` keyword for `Meta`, so that a custom annotated type could be created.

```python
T = TypeVar("T")
DefaultNone = Annotated[Optional[T], msgspec.Meta(default=None)]
NoDefault = Annotated[Unionl[T, UnsetType], msgspec.Meta(default=UNSET)]

class SomeClass(msgspec.Struct):
    field1: DefaultNone[str]
    field2: NoDefault[int]
```
If I just overlooked a possibility to do just that, please let me know!

**Comment by jcrist** [comment]
Unfortunately this isn't how python type annotations work. `msgspec` works out-of-the-box with standard python static analysis tools like `mypy`/`pyright`, meaning no msgspec-specific typing extensions need to be installed or configured. As such, we need to match dataclass semantics, and one of those semantics is that only parameters with default values specified may be optional, all other parameters are required.

The naming of `typing.Optional` is a bit unfortunate - it doesn't mean that the value is "optional", it means that it may exist or be `None`. If you look closely, you can see that `typing.Optional[int]` is just syntactic sugar for `Union[int, None]` (or `int | None`).

```python
In [1]: import typing

In [2]: typing.Optional[int] == typing.Union[int, None]  # these are the same
Out[2]: True

In [3]: typing.Optional[int].__origin__  # Optional[T] returns a union of T with None
Out[3]: typing.Union
```

I recognize that the typing here may feel a bit verbose, but since we want to stick with standard python type annotations, then these are the semantics we must use. If you're coming from pydantic V1 (where `Optional` did mark a field as not required), note that they've removed this behavior in pydantic V2 to be compatible with standard Python type annotations.

**Comment by ml31415** [comment]
Alright, that's understandable. Thanks!
