### ISSUE TITLE
Support encoding `asyncpg` `UUID` types

### ISSUE THREAD

**Issue by jcrist** [jcrist/msgspec#428]
### Description

(Original request here: https://github.com/litestar-org/litestar/issues/1785)

`asyncpg` is a popular SQL library that includes its own `UUID` type. This type is not technically a subclass of `uuid.UUID`, but they hack cpython to make it appear to be one: https://github.com/MagicStack/py-pgproto/blob/a4178145cd7cc3a44eee20cfc9e8b94a7fed2053/uuid.pyx#L307-L328.

If we do a full isinstance check for uuid types and "subclasses" then our current encoding logic should work natively for these types. Some care will need to be taken that this isinstance check is at the tail end of all branches (since it's more costly than a type equivalence check), but overall I wouldn't expect a perf hit here.

**Comment by provinzkraut** [comment]
> This type is not technically a subclass of `uuid.UUID`, but they hack cpython to make it appear to be one

Thanks for looking into this! I expected something like that because the stub files and runtime information didn't add up but I didn't have the time to look into it further. We'll close the issue on our side then.

<hr>

Can you elaborate on how this will not impact performance? I would have suspected a slight performance impact, although probably a negligible one.

**Comment by jcrist** [comment]
> Can you elaborate on how this will not impact performance? I would have suspected a slight performance impact, although probably a negligible one.

Sorry, that's basically what I meant. The cost of an `isinstance` check here is more than a simple type equality, but should be mostly negligible compared to other operations.
