### ISSUE TITLE
Bug serializing byte strings into JSON

### ISSUE THREAD

**Issue by Goldziher** [jcrist/msgspec#476]
### Description

Hi @jcrist 

So Im working on our v2 pydantic support and I encountered a strange issue. When I pass the following values into the encoder (`msgspec.json.Encoder.encode`) the field called `conbytes` gets mangaled.

This is the dictionary of values I get as output from Pydantic (using its `model.model_dump` method), which is passed to the encoder:

```python
{
    "path": PosixPath("example"),
    "email_str": "info@example.org",
    "name_email": NameEmail(name="info", email="info@example.org"),
    "color": Color("white", rgb=(255, 255, 255)),
    "bytesize": 100,
    "secret_str": SecretStr("**********"),
    "secret_bytes": SecretBytes(b"**********"),
    "payment_card_number": "4000000000000002",
    "constr": "hello",
    "conbytes": b"hello",
    "condate": datetime.date(2023, 7, 8),
    "condecimal": Decimal("3.14"),
    "confloat": 1.0,
    "conset": {1},
    "confrozenset": frozenset({1}),
    "conint": 1,
    "conlist": [1],
}
```

We have logic to handle all the types there, but the failure happens on the conbytes field - which is actualy simply a bytes field wrapped in Annotated. This is what is outputted there as json:

```json
{
  "path": "example",
  "email_str": "info@example.org",
  "name_email": "info <info@example.org>",
  "color": "white",
  "bytesize": 100,
  "secret_str": "**********",
  "secret_bytes": "**********",
  "payment_card_number": "4000000000000002",
  "constr": "hello",
  "conbytes": "aGVsbG8=",
  "condate": "2023-07-08",
  "condecimal": "3.14",
  "confloat": 1.0,
  "conset": [1],
  "confrozenset": [1],
  "conint": 1,
  "conlist": [1]
}

```

And this is what i get from pydantic when I use its `model.model_dump_json` method:

```json
{
  "path": "example",
  "email_str": "info@example.org",
  "name_email": "info <info@example.org>",
  "color": "white",
  "bytesize": 100,
  "secret_str": "**********",
  "secret_bytes": "**********",
  "payment_card_number": "4000000000000002",
  "constr": "hello",
  "conbytes": "hello",
  "condate": "2023-07-08",
  "condecimal": "3.14",
  "confloat": 1.0,
  "conset": [1],
  "confrozenset": [1],
  "conint": 1,
  "conlist": [1]
}
```

As you can see, msgspec is outputting:

```text
"conbytes": "aGVsbG8="
```

Instead of the expected:

```text
"conbytes": "hello"
```

**Comment by jcrist** [comment]
This is not a bug, and is intended.

Unlike MessagePack, JSON doesn't have a native binary type. To encode binary data as part of a JSON message, it's typical practice to `base64` encode the value. This is what golang's JSON does for `byte[]` types, and it's what `msgspec` does for `bytes`/`bytearray` types ([documented here](https://jcristharif.com/msgspec/supported-types.html#bytes-bytearray-memoryview)).

Pydantic takes a naive approach to handling `bytes`/`bytearray` types and tries to coerce them to utf-8 encoded strings. I'm skeptical of the usefulness of this - if your `bytes` objects must contain valid utf-8, then why not store them in-memory as `str` types anyway? This also doesn't work for arbitrary bytes objects, only for those that contain valid utf-8.

Pydantic V2 adds a new `Base64Bytes`/`Base64Str` type to represent base64 encoded data, until V2 there wasn't a clean built-in way to represent this data.

---

Anyway, since msgspec doesn't support pydantic models out-of-the-box, I suspect you're calling `model_dump()` in the `enc_hook` for msgspec. If you switch to `model_dump(mode="json")` it will apply pydantic's standard serializer transforms itself, so none of this logic will need to be handled by litestar/msgspec itself.

**Comment by Goldziher** [comment]
Cheers, I followed through on the advice and it solved the issue
