### ISSUE TITLE
Coerce ints into strings in `strict=False` mode

### ISSUE THREAD

**Issue by Goldziher** [jcrist/msgspec#477]
### Description

Hi again,

So I encountered an issue when parsing data coming over the wire using the `strict=False` option. The following will throw an exception:

```python
def test_minimal_coercion() -> None:
    @dataclass
    class MultiPartFormWithMixedFields:
        tags: List[str]

    result = convert({"tags": [1, 2, 3]}, MultiPartFormWithMixedFields, strict=False)
    assert result.tags
```

I assumed that with `strict=False` the integers will simply be coerced into strings, but this is not working.

**Comment by jcrist** [comment]
We don't support this currently, and I don't think we should.

`strict=False` is to apply more coercion rules when parsing data from an unstructured input (generally protocols that only really have a `str` type). Things like querystrings, environment variables, or multipart form data (as seen here).

In these cases we want to have a nice way to coerce strings *to* other types. So if `strict=False`, `msgspec` will happily coerce `"123"` into `123`. This is needed, since things like form data only have string values.

For more structured protocols (things that can represent an `int` as distinct from a `str`) I don't think we want to support this kind of coercion. Any value technically has a string representation, but if a field expects a `str` and receives an `int` (or `float`) I'd view it as a bug to coerce implicitly to a `str`.

For an added data point, Pydantic V1 used to support coercing `int -> str`, but they intentionally removed it in V2.

```python
In [1]: import pydantic

In [2]: pydantic.__version__
Out[2]: '2.0.2'

In [3]: class Test(pydantic.BaseModel):
   ...:     x: str
   ...: 

In [4]: Test(x=1)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[4], line 1
----> 1 Test(x=1)

File ~/miniconda3/envs/msgspec/lib/python3.9/site-packages/pydantic/main.py:150, in BaseModel.__init__(__pydantic_self__, **data)
    148 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    149 __tracebackhide__ = True
--> 150 __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)

ValidationError: 1 validation error for Test
x
  Input should be a valid string [type=string_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.1.2/v/string_type
```

**Comment by Goldziher** [comment]
aight... i guess we will need to document this on our end.
