### ISSUE TITLE
encode to `str` support

### ISSUE THREAD

**Issue by Olegt0rr** [jcrist/msgspec#514]
### Description

I often use `aiohttp` client and it requires `Callable -> str`
Is there any support for encoding to string instead of bytes?

Or should I use something like that?
```python
encoder = json.Encoder()
session = ClientSession(
    ...,
    json_serialize=lambda obj: str(encoder.encode(obj)),
)
```

**Comment by jcrist** [comment]
No, there's no support for encoding to a string value, and I'd be opposed to adding one. JSON is best represented in python as a `bytes` object containing UTF-8 encoded JSON.

There was an open issue in aiohttp to add support for the json encoder returning bytes directly (https://github.com/aio-libs/aiohttp/issues/4482), but that was rejected by the main maintainer. You're welcome to comment there.

Otherwise, there are two options:

- Do as you're doing above and convert the output from msgspec to a `str`. Note that your example code is incorrect, you'd want something like:


  ```python
  session = ClientSession(json_serialize=lambda obj: msgspec.json.encode(obj).encode())
  ```

  This is easy and is likely efficient enough. It does result in unnecessary unicode encoding/decoding though, and an unnecessary allocation.

- Manually construct the client payload yourself. This is more work, but would allow you to avoid the unnecessary utf-8 encode/decode. Whether that matters would require some benchmarking of your application. It'd be something like (untested):

  ```python
  session = aiohttp.ClientSession()
  
  session.request(..., data=aiohttp.BytesPayload(msgspec.json.encode(obj), content_type="application/json"))
  ```

**Comment by Olegt0rr** [comment]
@jcrist, 

Your example also incorrect, cause you can't `.encode(). bytes object. You can `.decode()` it.
```python
session = ClientSession(
    json_serialize=lambda obj: msgspec.json.encode(obj).decode()
)
```

My example also works if you'll add encoding :D 
```python
json_serialize=lambda obj: str(encoder.encode(obj), "utf-8")
```

**Comment by jcrist** [comment]
Gah, you're right. That's what I get for writing code examples without ever running them. Also TIL about the `encoding` argument to `str`.
