### ISSUE TITLE
Decoding a struct which references the same type results in an error

### ISSUE THREAD

**Issue by spacemanspiff2007** [jcrist/msgspec#525]
### Description

Creating a struct which references the same type works fine.
Encoding also works as expected.
Decoding however throws a very unexpected error

````python
import msgspec


class MyStruct(msgspec.Struct):
    a: int
    b: list['MyStruct']


print('Encode')
obj = MyStruct(a=1, b=[MyStruct(a=2, b=[])])
print(msgspec.json.encode(obj))

print('\nDecode')
data = '[{"a":1, "b":["a":2, "b":[]]}]'
print(msgspec.json.decode(data, type=list[MyStruct]))
````

Output:
````
Encode
b'{"a":1,"b":[{"a":2,"b":[]}]}'

Decode
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    print(msgspec.json.decode(data, type=list[MyStruct]))
TypeError: Type ''MyStruct'' is not supported
````

Is this currently not supported?

**Comment by jcrist** [comment]
This is supported, looks to me like a Python version specific bug. Some quick notes after investigating:

- Your code above runs fine on Python 3.11, but fails on earlier versions
- Switching to `typing.List["MyStruct"]` instead of `list["MyStruct"]` fixes the problem on all versions. The issue appears to be with how `typing._eval_type` handles `list[...]` in older python versions.

Two workaround options for now. These should work on all python versions supported:

- Use `typing.List` instead of `list`
- Or instead of using a literal string, use `from __future__ import annotations` to delay annotation evaluation.

```python
from __future__ import annotations

import msgspec


class MyStruct(msgspec.Struct):
    a: int
    b: list[MyStruct]


print('Encode')
obj = MyStruct(a=1, b=[MyStruct(a=2, b=[])])
print(msgspec.json.encode(obj))

print('\nDecode')
data = '[{"a":1, "b":[{"a":2, "b":[]}]}]'
print(msgspec.json.decode(data, type=list[MyStruct]))
```

**Comment by spacemanspiff2007** [comment]
Interesting. I'm running Python 3.10 and your analysis seems to be spot on.

The following works:

````python
from __future__ import annotations
    ...
    b: list[MyStruct]
````

or quoting the whole type hint:
````python
    b: 'list[MyStruct]'
````

Thank you very much for the very fast reply and the thorough analysis.
