### ISSUE TITLE
maximum recursion depth exceeded while deserializing an object

### ISSUE THREAD

**Issue by levsh** [jcrist/msgspec#551]
### Description

Hi!
Is it possible to convert object with cyclic refs?
For example, from orm model with relationships.
```python
In [1]: import msgspec

In [2]: class A(msgspec.Struct):
   ...:     b: 'B' = None
   ...:     

In [3]: class B(msgspec.Struct):
   ...:     a: A = None
   ...:     

In [4]: a = {'b': None}

In [5]: b = {'a': None}

In [6]: a['b'] = b

In [7]: b['a'] = a

In [8]: msgspec.convert(a, A)
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
Cell In[8], line 1
----> 1 msgspec.convert(a, A)

RecursionError: maximum recursion depth exceeded while deserializing an object
```

**Comment by jcrist** [comment]
Sorry, but we won't be able to handle cyclic datastructures.

`msgspec` is for encoding/decoding JSON-like data. Since JSON doesn't support cyclic datastructures, they're not supported by our datamodel. Neither other JSON libraries (`json`, `orjson`, `rapidjson`, ...) nor other validation libraries (`pydantic`/`cattrs`/...) support this use case, so we're not unique here.

**Comment by levsh** [comment]
@jcrist thanks for the explanation.
Is it acceptable to add a callback (as an optional argument to the `convert` function) similar to `dec_hook` but for all data types not only custom? That allows user to write its own algorithm on top of `convert` to handle cyclic refs.
