### ISSUE TITLE
Renaming fields for dataclasses

### ISSUE THREAD

**Issue by tekumara** [jcrist/msgspec#553]
### Description

I'd love to be able to rename fields when using dataclasses, similar to [Structs](https://jcristharif.com/msgspec/structs.html#renaming-fields), eg:

```python
@dataclass(frozen=True)
class Client:
    id: Annotated[int, msgspec.Meta(ge=0)]
    first_name: Annotated[str, msgspec.Meta(name="firstName")]
    lastName: str
```

**Comment by jcrist** [comment]
See also #372, for the same request but for attrs types.

While possible, I'm a bit reluctant to expand msgspec-specific features exposed in non-msgspec container types. Support for `dataclasses`/`attrs` types was intended to make it easy to use `msgspec` with existing codebases. You can import `msgspec` and start encoding/decoding objects without forcing you to convert existing dataclasses to `Struct` types immediately. However, once you need msgspec-specific configuration on a type, I don't see a reason to stick with `dataclasses` over `Struct` types. Structs are more performant, more featureful, and should be compatible with most API-consumers of dataclass types.

Is there a reason you'd prefer to use `dataclasses` here rather than migrating to `msgspec.Struct` types?

**Comment by tekumara** [comment]
I've given `msgspec.Struct` a look and it'll be a drop-in replacement so happy to go with that. Thank you!
