### ISSUE TITLE
Please add Discussions

### ISSUE THREAD

**Issue by giridhart** [jcrist/msgspec#578]
### Description

Please add Github discussions to this project. https://docs.github.com/en/discussions/quickstart
I have a question but not sure where to ask.
There are some questions in `Issues` but when I tried to create one there seems to be only two types of issues.
Thank you

**Comment by jcrist** [comment]
I'd rather keep all conversation in "Issues" rather than add a new place for users to look under "Discussions". Some questions may turn into feature requests, and some feature requests may be questions in disguise. It makes more sense to me to keep everything in on e spot.

I've added a new "Question" issue template in #581, and also enabled blank issues. Please ask feel free to open a new issue to ask your question.
