### ISSUE TITLE
maybe an exception should be thrown when there are bytes in the dict passed to json.encode

### ISSUE THREAD

**Issue by bymoye** [jcrist/msgspec#584]
### Description

In the example, they are not equal because I used bytes for one of the fields in the dict:
```python

temp = {
    "a": 1,
    "b": "2",
    "c": 3.0,
    "d": True,
    "f": [1, 2, 3],
    "g": b"123",
    "i": {
        "a": {"c": 3, "l": [2, 5]},
        "b": {"c": 3, "l": [2, 5]},
    },
}
a = msgspec.json.encode(temp)
b = msgspec.json.decode(a)
assert b == temp

```

maybe it should throw an exception like orjson: Type is not JSON serializable: bytes

**Comment by jcrist** [comment]
For JSON binary objects (`bytes`, `bytearray`, and `memoryview`) serialize as base64-encoded strings. This is intentional and is documented [here](https://jcristharif.com/msgspec/supported-types.html#bytes-bytearray-memoryview). To decode back into a bytes object you'd need to provide a `type` to the `decode` method to tell msgspec to coerce the string back to a bytes object.
