### ISSUE TITLE
How to add multiple Mixins that declare additional fields?

### ISSUE THREAD

**Issue by Yolley** [jcrist/msgspec#590]
### Question

Some of my structs share common fields that I would like declare as mixins and inherit from these Mixins in Struct implementation like so:

```python
class ActiveMixin:
    active: bool


class CreatedUpdatedMixin:
    created: datetime
    updated: datetime


class ImplementationStruct(msgspec.Struct, ActiveMixin, CreatedUpdatedMixin):
    field_1: str
```

Fields that were declared in Mixins are not added to `__struct_fields__`, therefore there are not parsed when I try to decode a JSON with these fields presented. And it doesn't matter whether I change order of inheritance or not.

I've tried to to do differently so that each Mixin inherits from msgspec.Struct
```python
class ActiveMixin(msgspec.Struct):
    active: bool


class CreatedUpdatedMixin(msgspec.Struct):
    created: datetime
    updated: datetime


class ImplementationStruct(ActiveMixin, CreatedUpdatedMixin):
    field_1: str
```

But now I get an error
```
    class ImplementationStruct(ActiveMixin, CreatedUpdatedMixin):
TypeError: multiple bases have instance lay-out conflict
```

So, is it possible to declare Mixins somehow and inherit from them to no not duplicate declaration of the same fields in each Struct?

**Comment by wikiped** [comment]
@Yolley 
You might want to have a look at [Tagged Unions](https://jcristharif.com/msgspec/structs.html#tagged-unions) part of the docs. There is an example of inheritance.

Since `Struct`s behave like builtin classes (which in most cases are C-based as well) - one way to avoid lay-out conflict is to follow [Single Inheritance](https://learn.microsoft.com/en-us/cpp/cpp/single-inheritance) rule for every descendant from a `Base` class. I.e.:

```python
from msgspec import Struct


class Base(Struct, kw_only=True):  # kw_only=True - is just an example
    """This will ensure all children will have the same ___struct_config__"""
    ...


class TimedStamped(Base):
    created: datetime
    updated datetime


class ActiveStamped(TimeStamped):
    active: bool

```
