### ISSUE TITLE
Doc suggestions

### ISSUE THREAD

**Issue by ian-r-rose** [jcrist/msgspec#67]
Overall I thought the docs were great. Clear, motivated, and succinct. Here are a few disorganized thoughts/suggestions I had when reading them:

* I love the benchmarking note
* Typo: encode -> decode: https://github.com/jcrist/msgspec/blob/7048ab985c7639f4841ead157d317f8420b34d3e/docs/source/usage.rst?plain=1#L64
* I found this sentence confusing. It seemed like there was a "but" clause coming, then there was none: https://github.com/jcrist/msgspec/blob/7048ab985c7639f4841ead157d317f8420b34d3e/docs/source/usage.rst?plain=1#L98-L100  . Is there some caveat I'm not understanding?
* In a lot of the sample code snippets I found myself wanting to see more [PEP 604](https://www.python.org/dev/peps/pep-0604/) and [PEP 585](https://www.python.org/dev/peps/pep-0585/) syntax for type annotations. This would remove some imports, at the cost of a `__future__` import, I suppose. I am not sure what the current state of the art is for the places where a type is used in a value position, as is the case for your `Decoder` class. Probably it's not backwards compatible enough for you.
* :clap: `Invalid enum value 'GRAPE'`
* I found the initial `asarray` discussion a bit confusing in `Usage`. Mostly I was initially confused disambiguating between C arrays, numpy arrays, and the serialization format. It became clearer as I read further, but my initial contact was a little muddled.
* Does `msgspec` support [implicit Optional](https://www.python.org/dev/peps/pep-0484/#union-types) (not recommended, but supported by most type checkers)?
* Ooh, a tantalizing reference to pattern matching. It would be cool to see an example of that.
* Does the ["Avoid Decoding Unused Fields"](https://jcristharif.com/msgspec/perf-tips.html#avoid-decoding-unused-fields) trick work with `asarray=True`?
* Seems to be an escaping issue with `"\n"` in the docs here: https://github.com/jcrist/msgspec/blob/7048ab985c7639f4841ead157d317f8420b34d3e/docs/source/perf-tips.rst?plain=1#L151
* Can `enc_hook` also be given to add custom handling to a type the `msgspec` *does* natively support? Like, if I wanted to use it to truncate a float or something, could I do it? I don't know if it's ever a good idea, but based on my reading of the docs, that is not currently possible.

It's not a problem with the docs, but I also found myself wondering if it was in scope to have any translation code to things like openapi/jsonschema.

**Comment by jcrist** [comment]
Thanks @ian-r-rose!!! These are excellent notes - I'm going to leave this open until I clarify the docs on these points.

Answering a few of your questions inline:

>  I am not sure what the current state of the art is for the places where a type is used in a value position, as is the case for your Decoder class. Probably it's not backwards compatible enough for you.

Yeah, those won't work on older versions of python. PEP 585 & PEP 604 only work with older versions of python when written as annotations (anything after the `:`), providing that `from __future__ import annotations` is applied (which makes the annotations strings, which runtime tooling then needs to interpret). This is because mypy/pyright/whatever are interpreting the annotations themselves, rather than relying on the standard python objects doing so. Since we need the types at runtime, we'd have to be able to interpret the newer syntax manually, since the stdlib won't. Other libraries that make use of annotations for runtime effects (e.g. pydantic) also have the same restrictions.

> Does msgspec support [implicit Optiona](https://www.python.org/dev/peps/pep-0484/#union-types)

No, but it won't error nicely (yet) either if the default value is invalid for the specified type. Mypy & pyright will catch that error statically though, so that's a partial solution.

 > Does the ["Avoid Decoding Unused Fields"](https://jcristharif.com/msgspec/perf-tips.html#avoid-decoding-unused-fields) trick work with asarray=True?

Yes.

> Can enc_hook also be given to add custom handling to a type the msgspec does natively support? Like, if I wanted to use it to truncate a float or something, could I do it? 

No, not currently. If a type is natively supported, how it's handled can't be modified. Only custom types can be customized.

 > It's not a problem with the docs, but I also found myself wondering if it was in scope to have any translation code to things like openapi/jsonschema.

I think some utilities for generating jsonschema/openapi specs from type definitions would be in scope. Since we don't support all the type annotations provided by jsonschema though (and probably won't, I don't see all jsonschema features as in scope), automatically generating type definitions from a schema wouldn't be in scope.
